export const MANAGE_ATTENDANCE_MEMBERS_DATA = "MANAGE_ATTENDANCE_MEMBERS_GET";
export const MANAGE_ATTENDANCE_MEMBERS_SUCCESS = "MANAGE_ATTENDANCE_MEMBERS_SUCCESS";
export const MANAGE_ATTENDANCE_MEMBERS_FAILED = "MANAGE_ATTENDANCE_MEMBERS_FAILED";
